### ISSUE TITLE
java.lang.NoSuchMethodException: No setter for property 'threadCount'

### ISSUE THREAD

**Issue by wzhonggo** [andrehertwig/spring-boot-starter-quartz#2]
Hi , 
I get error when set **org.quartz.threadPool.threadCount** property. I remove this property is will ok. It is a bug or my mistake?
``` xml
<dependency>
			<groupId>de.chandre.quartz</groupId>
			<artifactId>spring-boot-starter-quartz</artifactId>
			<version>1.0.1</version>
			<exclusions>
				<exclusion>
					<groupId>com.mchange</groupId>
					<artifactId>c3p0</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.mchange</groupId>
					<artifactId>mchange-commons-java</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.zaxxer</groupId>
					<artifactId>HikariCP-java6</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

``` properties
org.quartz.scheduler.instanceName=quartzScheduler
org.quartz.scheduler.instanceId=AUTO
org.quartz.threadPool.threadCount=5
#org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
#org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.class = org.springframework.scheduling.quartz.LocalDataSourceJobStore
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.useProperties=true
org.quartz.jobStore.misfireThreshold=60000
org.quartz.jobStore.tablePrefix=QRTZ_

org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval=20000

org.quartz.scheduler.skipUpdatequartz.Check=true
```

``` properties
#quzrtz
quartz.persistence.persisted=true
quartz.properties-config-location=classpath:/quartz.properties
```

``` txt
2017-11-03 12:08:12,145 [restartedMain] ERROR org.springframework.boot.SpringApplication:771 - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'autoSchedulerFactory' defined in class path resource [de/chandre/quartz/spring/QuartzSchedulerAutoConfiguration.class]: Invocation of init method failed; nested exception is org.quartz.SchedulerException: ThreadPool class 'org.springframework.scheduling.quartz.LocalTaskExecutorThreadPool' props could not be configured. [See nested exception: java.lang.NoSuchMethodException: No setter for property 'threadCount']
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.labimo.PublisherApplication.main(PublisherApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.quartz.SchedulerException: ThreadPool class 'org.springframework.scheduling.quartz.LocalTaskExecutorThreadPool' props could not be configured.
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:849)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:595)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:478)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 21 common frames omitted
Caused by: java.lang.NoSuchMethodException: No setter for property 'threadCount'
	at org.quartz.impl.StdSchedulerFactory.setBeanProps(StdSchedulerFactory.java:1447)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:847)
	... 26 common frames omitted
```

**Comment by andrehertwig** [comment]
Which version of Spring Boot do you use?
Which version is spring-context-support?
Do you override the Quartz version? If so, which Quartz version do you use?

BTW: This autostarter is designed to use Quartz >= 2.2.3

**Comment by wzhonggo** [comment]
- Spring-boot version is 1.5.6.RELEASE
- Spring-context-support version is 4.3.10.RELEASE
- Quartz version is 2.3.0

**Comment by andrehertwig** [comment]
Did you check, that there is really no other quartz artifact in your classpath/build artifact?
because i also have some unitest overriding the thread count and they are working fine

**Comment by wzhonggo** [comment]
Hi
It is only a quartz artifact in my classpath.  It is a maven project, so it is only have one version even you have mutil version in pom.xml.  I do not know this error.But i hava disable **org.quartz.threadPool.threadCount** , and it is ok now. Thank you very much for this project.

**Comment by andrehertwig** [comment]
Hi
I Updated the documentation about the usage. Do you tried to explicitly add the package to component scanning?
`@ComponentScan(basePackages={"your.packages", "de.chandre.quartz.spring"})`

**Comment by wzhonggo** [comment]
Hi
It is still show error when use `@ComponentScan(basePackages={"your.packages", "de.chandre.quartz.spring"})` 

Error message:
`Caused by: java.lang.NoSuchMethodException: No setter for property 'threadCount'
	at org.quartz.impl.StdSchedulerFactory.setBeanProps(StdSchedulerFactory.java:1447)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:847)
	... 42 common frames omitted`

I not see **threadCount** in **org.quartz.impl.StdSchedulerFactory** with Quartz 2.3.0. Is it deleted **threadCount** property in **org.quartz.impl.StdSchedulerFactory**?

**Comment by andrehertwig** [comment]
Hi
I think you have a configuration problem.
Do you use a custom task executor or set the org.quartz.threadPool.class explicitely?

because the exception tells you -> Caused by: org.quartz.SchedulerException: ThreadPool class 'org.springframework.scheduling.quartz.LocalTaskExecutorThreadPool' props could not be configured.

LocalTaskExecutorThreadPool.class doesn't has a property for threadCount. If you use a custom task executor you can set the thread there or use SimpleThreadPool (leave "org.quartz.threadPool.class" empty and do not set a taks executor manually).

please check springs SchedulerFactoryBean#initSchedulerFactory
and From Quartz StdSchedulerFactory#instantiate
```java 
String tpClass = cfg.getStringProperty(PROP_THREAD_POOL_CLASS, SimpleThreadPool.class.getName());

        if (tpClass == null) {
            initException = new SchedulerException(
                    "ThreadPool class not specified. ");
            throw initException;
        }
        try {
            tp = (ThreadPool) loadHelper.loadClass(tpClass).newInstance();
        } catch (Exception e) {
            initException = new SchedulerException("ThreadPool class '"
                    + tpClass + "' could not be instantiated.", e);
            throw initException;
        }
        tProps = cfg.getPropertyGroup(PROP_THREAD_POOL_PREFIX, true);
        try {
            setBeanProps(tp, tProps);
        } catch (Exception e) {
            initException = new SchedulerException("ThreadPool class '"
                    + tpClass + "' props could not be configured.", e);
            throw initException;
        }
```

**Comment by wzhonggo** [comment]
Hi
The reason is use  custom task executor. When i delete below code in SchedulerConfig Class [(SchedulerConfig Simple)](https://github.com/andrehertwig/spring-boot-starter-quartz#additional-things) , it is success with threadCount property . If not use custome task,  threadCount  will be set in springs SchedulerFactoryBean#initSchedulerFactory.

``` java
@Bean
    public QuartzSchedulerFactoryOverrideHook quartzSchedulerFactoryOverrideHook() {
        return new QuartzSchedulerFactoryOverrideHook() {
            @Override
            public SchedulerFactoryBean override(SchedulerFactoryBean factory, QuartzSchedulerProperties properties, Properties quartzProperties) {
                factory.setTaskExecutor(Executors.newFixedThreadPool(10));
                return factory;
            }
        };
    }
```
Thank you again

**Comment by andrehertwig** [comment]
It's already closed, but now i had the time to create a testcase for that. check commit #ddf0e59 above if you want to use a custom task executor

**Comment by wayss000** [comment]
> Hi
> The reason is use custom task executor. When i delete below code in SchedulerConfig Class [(SchedulerConfig Simple)](https://github.com/andrehertwig/spring-boot-starter-quartz#additional-things) , it is success with threadCount property . If not use custome task, threadCount will be set in springs SchedulerFactoryBean#initSchedulerFactory.
> 
> ```java
> @Bean
>     public QuartzSchedulerFactoryOverrideHook quartzSchedulerFactoryOverrideHook() {
>         return new QuartzSchedulerFactoryOverrideHook() {
>             @Override
>             public SchedulerFactoryBean override(SchedulerFactoryBean factory, QuartzSchedulerProperties properties, Properties quartzProperties) {
>                 factory.setTaskExecutor(Executors.newFixedThreadPool(10));
>                 return factory;
>             }
>         };
>     }
> ```
> 
> Thank you again

I also encountered this problem. My solution is to modify the id of bean `ThreadPoolTaskExecutor`, from `taskExecutor` to `otherTaskExecutor`. So, as long as the bean id is not a `taskExecutor`.
